/**
 * TokenManager — generates, validates, revokes, and auto-cleans time-limited tokens.
 *
 * Responsible for:
 * - Generating cryptographically random tokens with configurable expiration
 * - Validating tokens against the active store (existence + expiration check)
 * - Revoking individual tokens or clearing all tokens on shutdown
 * - Periodic cleanup of expired tokens (every 60 seconds)
 * - Providing an `authenticate` adapter function compatible with CommandCenter config
 */

import { randomBytes } from 'node:crypto';

// ---------------------------------------------------------------------------
// Interfaces
// ---------------------------------------------------------------------------

export interface StoredToken {
  token: string;
  expiresAt: number; // Unix timestamp in ms
  operatorId: string;
  permissions: string[];
}

export interface TokenGenerationResult {
  token: string;
  expiresAt: number;
}

export interface TokenCredentials {
  operatorId: string;
  permissions: string[];
}

// ---------------------------------------------------------------------------
// TokenManager class
// ---------------------------------------------------------------------------

export class TokenManager {
  private readonly tokens: Map<string, StoredToken> = new Map();
  private readonly tokenExpirationSeconds: number;
  private cleanupTimer: ReturnType<typeof setInterval> | null = null;

  constructor(tokenExpirationSeconds: number) {
    this.tokenExpirationSeconds = tokenExpirationSeconds;
  }

  // -------------------------------------------------------------------------
  // Token Generation (Task 2.1)
  // -------------------------------------------------------------------------

  /**
   * Generate a new token for the given operator with specified permissions.
   * Uses crypto.randomBytes(32) to produce a 64-character hex token.
   * Stores the token in memory and returns the token value with its expiration.
   */
  generateToken(operatorId: string, permissions: string[]): TokenGenerationResult {
    const token = randomBytes(32).toString('hex');
    const expiresAt = Date.now() + this.tokenExpirationSeconds * 1000;

    const stored: StoredToken = {
      token,
      expiresAt,
      operatorId,
      permissions,
    };

    this.tokens.set(token, stored);

    return { token, expiresAt };
  }

  // -------------------------------------------------------------------------
  // Token Validation (Task 2.2)
  // -------------------------------------------------------------------------

  /**
   * Validate a token string. Returns operator credentials if the token exists
   * and has not expired, or undefined otherwise.
   */
  validateToken(token: string): TokenCredentials | undefined {
    const stored = this.tokens.get(token);

    if (!stored) {
      return undefined;
    }

    if (Date.now() >= stored.expiresAt) {
      return undefined;
    }

    return {
      operatorId: stored.operatorId,
      permissions: stored.permissions,
    };
  }

  // -------------------------------------------------------------------------
  // Token Revocation and Cleanup (Task 2.3)
  // -------------------------------------------------------------------------

  /**
   * Revoke a specific token immediately.
   * Returns true if the token existed and was removed, false otherwise.
   */
  revokeToken(token: string): boolean {
    return this.tokens.delete(token);
  }

  /**
   * Clear all tokens from the store and stop the cleanup timer.
   * Used during shutdown to release all state.
   */
  clearAll(): void {
    this.tokens.clear();
    this.stopCleanup();
  }

  /**
   * Start the periodic cleanup timer that removes expired tokens every 60 seconds.
   */
  startCleanup(): void {
    if (this.cleanupTimer !== null) {
      return; // already running
    }

    this.cleanupTimer = setInterval(() => {
      const now = Date.now();
      for (const [key, stored] of this.tokens) {
        if (now >= stored.expiresAt) {
          this.tokens.delete(key);
        }
      }
    }, 60_000);

    // Allow the process to exit even if the timer is still active
    if (this.cleanupTimer.unref) {
      this.cleanupTimer.unref();
    }
  }

  /**
   * Stop the periodic cleanup timer.
   */
  stopCleanup(): void {
    if (this.cleanupTimer !== null) {
      clearInterval(this.cleanupTimer);
      this.cleanupTimer = null;
    }
  }

  // -------------------------------------------------------------------------
  // Authenticate Adapter (Task 2.4)
  // -------------------------------------------------------------------------

  /**
   * Inject a pre-existing token into the store. Used by the backend process
   * to load the initial token generated by the CLI launcher.
   */
  _injectToken(token: string, expiresAt: number, operatorId: string, permissions: string[]): void {
    this.tokens.set(token, { token, expiresAt, operatorId, permissions });
  }

  /**
   * Returns an authenticate function compatible with the CommandCenter config.
   * The returned function takes a token string and returns credentials or undefined.
   */
  getAuthenticateFn(): (token: string) => TokenCredentials | undefined {
    return (token: string) => this.validateToken(token);
  }
}
